### ISSUE TITLE
need little help 

### ISSUE THREAD

**Issue by zombiezooz25** [DaniDiazTech/Qtile-Config#7]
Hey i love your config but i suck at python ( i am going to start learning it).. i wanted to change my workspaces by mod + 1-9 but can't figure out how.. can you help a little

**Comment by DaniDiazTech** [comment]
Hello there, it's awesome you like my config. I suggest you make a fork and then apply all the changes you want.
Groups or "Workspaces" are generated by the **groups.py** file. At the same time, this file retrieves the icons or the name of the groups from the **icons.py** file.

![image](https://user-images.githubusercontent.com/64286838/153758959-e1ac971e-afab-4f43-aa9a-a9d6e93f7c41.png)

The only thing you must do is change the contents of the **group_icons** list inside the **icons.py**.

In your case, you would change this:

```python
# You can define a letter and its icon here
group_icons = ["B   ",
               "D  ",
               "T  ",
               "V  ",
               "M  ",
               "C  ",
               "E  ",
               "N  ",
               ]
```
to this:
```python
# You can define a letter and its icon here
group_icons = ["1",
               "2",
               "3",
               "4",
               "5",
               # and so forth
               ]
```
